// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLedAzulChange();
void onLedRojoChange();
void onLedVerdeChange();

float dht_humedad;
float dht_temperatura;
int HumedadSuelo;
int numero_muestra;
int sensorLluvia;
bool led_azul;
bool led_rojo;
bool led_verde;

void initProperties(){

  ArduinoCloud.addProperty(dht_humedad, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dht_temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(HumedadSuelo, READ, 120 * SECONDS, NULL);
  ArduinoCloud.addProperty(numero_muestra, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sensorLluvia, READ, 120 * SECONDS, NULL);
  ArduinoCloud.addProperty(led_azul, READWRITE, 120 * SECONDS, onLedAzulChange);
  ArduinoCloud.addProperty(led_rojo, READWRITE, 120 * SECONDS, onLedRojoChange);
  ArduinoCloud.addProperty(led_verde, READWRITE, 120 * SECONDS, onLedVerdeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
